# Generated by Django 3.1.1 on 2020-10-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201014_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.CharField(default='this is just to test the discription for the item ', max_length=100),
            preserve_default=False,
        ),
    ]
